/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.prjRend.telas;

import java.beans.PropertyVetoException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rhuan
 */
public class OperacoesBanco extends javax.swing.JFrame {

    /**
     * Creates new form OperacoesBanco
     */
    public OperacoesBanco() {
        initComponents();
        
        ////////////////////////////// importacao do icone das janelas
        ImageIcon icon = new ImageIcon(TelaEntrada.class.getResource("/br/com/prjRend/icones/icon.png"));
        this.setIconImage(icon.getImage());
        ////////////////////////////// importacao do icone das janelas
        
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lblUserNome = new javax.swing.JLabel();
        lblUserNome1 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        MenuBarCadastro = new javax.swing.JMenu();
        MenuBarCadastroSetores = new javax.swing.JMenuItem();
        MenuBarCadastroTrabalhos = new javax.swing.JMenuItem();
        MenuBarCadastroPecas = new javax.swing.JMenuItem();
        MenuBarCadastroTempo = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuBarCadastroFuncionarios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        MenuBarOpcoes = new javax.swing.JMenu();
        MenOptFecharEstaTela = new javax.swing.JMenuItem();
        MenOptFecharTudo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ROCA - Controle de Eficiência");

        desktop.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        lblUserNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUserNome.setText("Nome");

        lblUserNome1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUserNome1.setText("Administrador:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUserNome1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserNome)
                .addContainerGap(907, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(659, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserNome)
                    .addComponent(lblUserNome1))
                .addContainerGap())
        );

        desktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuBar.setPreferredSize(new java.awt.Dimension(312, 38));

        MenuBarCadastro.setText("Cadastro");
        MenuBarCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuBarCadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuBarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarCadastroActionPerformed(evt);
            }
        });

        MenuBarCadastroSetores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenuBarCadastroSetores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuBarCadastroSetores.setText("Setores");
        MenuBarCadastroSetores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuBarCadastroSetores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarCadastroSetoresActionPerformed(evt);
            }
        });
        MenuBarCadastro.add(MenuBarCadastroSetores);

        MenuBarCadastroTrabalhos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenuBarCadastroTrabalhos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuBarCadastroTrabalhos.setText("Trabalhos");
        MenuBarCadastroTrabalhos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuBarCadastroTrabalhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarCadastroTrabalhosActionPerformed(evt);
            }
        });
        MenuBarCadastro.add(MenuBarCadastroTrabalhos);

        MenuBarCadastroPecas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenuBarCadastroPecas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuBarCadastroPecas.setText("Operações");
        MenuBarCadastroPecas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuBarCadastroPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarCadastroPecasActionPerformed(evt);
            }
        });
        MenuBarCadastro.add(MenuBarCadastroPecas);

        MenuBarCadastroTempo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenuBarCadastroTempo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuBarCadastroTempo.setText("Valores Takt");
        MenuBarCadastroTempo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuBarCadastroTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarCadastroTempoActionPerformed(evt);
            }
        });
        MenuBarCadastro.add(MenuBarCadastroTempo);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem8.setText("Linhas de Produção");
        jMenuItem8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        MenuBarCadastro.add(jMenuItem8);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setText("Funcionários");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuBarCadastro.add(jMenuItem1);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem6.setText("Pausas Planejadas");
        jMenuItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        MenuBarCadastro.add(jMenuItem6);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setText("Pausas não Planejadas");
        jMenuItem2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuBarCadastro.add(jMenuItem2);

        MenuBarCadastroFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenuBarCadastroFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuBarCadastroFuncionarios.setText("Usuários Administradores");
        MenuBarCadastroFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuBarCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarCadastroFuncionariosActionPerformed(evt);
            }
        });
        MenuBarCadastro.add(MenuBarCadastroFuncionarios);

        MenuBar.add(MenuBarCadastro);

        jMenu1.setText("Relatórios");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem3.setText("Status das Linhas");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem4.setText("Histórico de Produção");
        jMenuItem4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        MenuBar.add(jMenu1);

        jMenu2.setText("Importações");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem5.setText("Importação de Horas");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        MenuBar.add(jMenu2);

        jMenu3.setText("Registros");
        jMenu3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem7.setText("Novo Apontamento");
        jMenuItem7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        MenuBar.add(jMenu3);

        MenuBarOpcoes.setText("Sair");
        MenuBarOpcoes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MenuBarOpcoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuBarOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBarOpcoesActionPerformed(evt);
            }
        });

        MenOptFecharEstaTela.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenOptFecharEstaTela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenOptFecharEstaTela.setText("Fechar esta tela");
        MenOptFecharEstaTela.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenOptFecharEstaTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOptFecharEstaTelaActionPerformed(evt);
            }
        });
        MenuBarOpcoes.add(MenOptFecharEstaTela);

        MenOptFecharTudo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenOptFecharTudo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenOptFecharTudo.setText("Fechar tudo");
        MenOptFecharTudo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenOptFecharTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOptFecharTudoActionPerformed(evt);
            }
        });
        MenuBarOpcoes.add(MenOptFecharTudo);

        MenuBar.add(MenuBarOpcoes);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        setSize(new java.awt.Dimension(1104, 737));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuBarCadastroPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarCadastroPecasActionPerformed
        TelaDeCadastroPecas pecas = new TelaDeCadastroPecas();
        desktop.add(pecas);
        pecas.setVisible(true);
        try {
            pecas.setMaximum(true); // Maximiza o JInternalFrame
        } catch (PropertyVetoException e) {
            e.printStackTrace(); // Trata a exceção caso a maximização falhe
        }
    }//GEN-LAST:event_MenuBarCadastroPecasActionPerformed

    private void MenuBarCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarCadastroFuncionariosActionPerformed
        TelaDeCadastroUsuarios usuarios = new TelaDeCadastroUsuarios();
        desktop.add(usuarios);
        usuarios.setVisible(true);
        try {
            usuarios.setMaximum(true); // Maximiza o JInternalFrame
        } catch (PropertyVetoException e) {
            e.printStackTrace(); // Trata a exceção caso a maximização falhe
        }
    }//GEN-LAST:event_MenuBarCadastroFuncionariosActionPerformed

    private void MenuBarCadastroSetoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarCadastroSetoresActionPerformed
        TelaDeCadastroSetores setores = new TelaDeCadastroSetores();
        desktop.add(setores);
        setores.setVisible(true);
        try {
            setores.setMaximum(true); // Maximiza o JInternalFrame
        } catch (PropertyVetoException e) {
            e.printStackTrace(); // Trata a exceção caso a maximização falhe
        }
    }//GEN-LAST:event_MenuBarCadastroSetoresActionPerformed

    private void MenuBarCadastroTrabalhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarCadastroTrabalhosActionPerformed
        TelaDeCadastroTrabalhos trabalhos = new TelaDeCadastroTrabalhos();
        desktop.add(trabalhos);
        trabalhos.setVisible(true);
        try {
            trabalhos.setMaximum(true); // Maximiza o JInternalFrame
        } catch (PropertyVetoException e) {
            e.printStackTrace(); // Trata a exceção caso a maximização falhe
        }
    }//GEN-LAST:event_MenuBarCadastroTrabalhosActionPerformed

    private void MenuBarCadastroTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarCadastroTempoActionPerformed
        TelaDeCadastroTakts tt = new TelaDeCadastroTakts();
        desktop.add(tt);
        tt.setVisible(true);
        try {
            tt.setMaximum(true); // Maximiza o JInternalFrame
        } catch (PropertyVetoException e) {
            e.printStackTrace(); // Trata a exceção caso a maximização falhe
        }
    }//GEN-LAST:event_MenuBarCadastroTempoActionPerformed

    private void MenOptFecharEstaTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOptFecharEstaTelaActionPerformed
        this.dispose();
        TelaEntrada ent = new TelaEntrada();
        ent.setVisible(true);
    }//GEN-LAST:event_MenOptFecharEstaTelaActionPerformed

    private void MenuBarOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarOpcoesActionPerformed

    }//GEN-LAST:event_MenuBarOpcoesActionPerformed

    private void MenOptFecharTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOptFecharTudoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenOptFecharTudoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaDeCadastroFuncionarios tf = new TelaDeCadastroFuncionarios();
        desktop.add(tf);
        tf.setVisible(true);
        try {
            tf.setMaximum(true); // Maximiza o JInternalFrame
        } catch (PropertyVetoException e) {
            e.printStackTrace(); // Trata a exceção caso a maximização falhe
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MenuBarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBarCadastroActionPerformed
        
    }//GEN-LAST:event_MenuBarCadastroActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        TelaDeCadastroParadas tcp = new TelaDeCadastroParadas();
        desktop.add(tcp);
        tcp.setVisible(true);
        try {
            tcp.setMaximum(true); // Maximiza o JInternalFrame
        } catch (PropertyVetoException e) {
            e.printStackTrace(); // Trata a exceção caso a maximização falhe
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TelaDeStatus status = new TelaDeStatus();
        desktop.add(status);
        status.setVisible(true);
        try {
            status.setMaximum(true); // Maximiza o JInternalFrame
        } catch (PropertyVetoException e) {
            e.printStackTrace(); // Trata a exceção caso a maximização falhe
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaRelatorioDeProducao prod = new TelaRelatorioDeProducao();
        desktop.add(prod);
        prod.setVisible(true);
        try {
            prod.setMaximum(true); // Maximiza o JInternalFrame
        } catch (PropertyVetoException e) {
            e.printStackTrace(); // Trata a exceção caso a maximização falhe
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TelaDeImportarHoras imp = new TelaDeImportarHoras();
        desktop.add(imp);
        imp.setVisible(true);
        try {
            imp.setMaximum(true); // Maximiza o JInternalFrame
        } catch (PropertyVetoException e) {
            e.printStackTrace(); // Trata a exceção caso a maximização falhe
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       TelaDeCadastroParadasPlanejadas tcpp = new TelaDeCadastroParadasPlanejadas();
        desktop.add(tcpp);
        tcpp.setVisible(true);
        try {
            tcpp.setMaximum(true); // Maximiza o JInternalFrame
        } catch (PropertyVetoException e) {
            e.printStackTrace(); // Trata a exceção caso a maximização falhe
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        TelaEscolherSetorDepois tesd = new TelaEscolherSetorDepois();
        tesd.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
    TelaDeCadastroLinhas te = new TelaDeCadastroLinhas();
    desktop.add(te);    
    te.setVisible(true);
    try {
            te.setMaximum(true); // Maximiza o JInternalFrame
        } catch (PropertyVetoException e) {
            e.printStackTrace(); // Trata a exceção caso a maximização falhe
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacoesBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacoesBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacoesBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacoesBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacoesBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenOptFecharEstaTela;
    private javax.swing.JMenuItem MenOptFecharTudo;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuBarCadastro;
    private javax.swing.JMenuItem MenuBarCadastroFuncionarios;
    private javax.swing.JMenuItem MenuBarCadastroPecas;
    private javax.swing.JMenuItem MenuBarCadastroSetores;
    private javax.swing.JMenuItem MenuBarCadastroTempo;
    private javax.swing.JMenuItem MenuBarCadastroTrabalhos;
    private javax.swing.JMenu MenuBarOpcoes;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblUserNome;
    public javax.swing.JLabel lblUserNome1;
    // End of variables declaration//GEN-END:variables
}
